version: '3.5'

services:
  laravel-app:
    build:
      context: './docker'
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=team
    networks:
      backend:
        aliases:
          - mysql-db
          
networks:
  backend:
    name: backend-network
